name: Build derived files
on:
  # Allows for on-demand build
  workflow_dispatch:
  # Automatically rebuilds when somebody edits a markdown file in
  # the kgs/ directory
  push:
    branches:
      - main
    paths:
      - 'docs/registry/kgs/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: snakemake/snakemake:v8.27.1
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Create local changes
        run: |
          touch docs/registry/kgs/*.md; snakemake -c2 --show-failed-logs --use-conda docs/registry/kgs.yaml docs/registry/index.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "ðŸš€ Automatically rebuilt derived files"
          committer: "GitHub Action <action@github.com>"
          title: 'Update KG registry metadata'
          body: |
            Recreates all KG registry metadata.
          assignees: balhoff
